[package]
name = "xboxemu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
ctrlc = "3.4.5"
env_logger = "0.11.5"
serde = "1.0.208"
ssmarshal = "1.0.0"
usb-gadget = "0.7.2"
usbd-hid-macros = "0.8.2"

